### PR TITLE
Heroku deploy improvements

### PR DESCRIPTION
**Pull request by aullman**
I ran into some issues when trying to deploy to Heroku. Here are some fixes that will make it easier for others in the future.

### CODE REVIEW

**Comment by aullman** [comment]
@aoberoi Waiting for a :+1: from you before I merge this one.

**Comment by aoberoi** [comment]
I like the changes, but I'm concerned about people who want to run locally and not on Heroku. We probably need good fallbacks so it's not ClearDB specifically, but any MySQL instance (and the same for SendGrid versus generic SMTP).

**Comment by aoberoi** [comment]
Oh wait, I just realized the code does handle these already. :+1:!

**Comment by aullman** [comment]
Thanks

**Pull request merged**
